### ISSUE TITLE
error in profile.puppetctl.sh

### ISSUE THREAD

**Issue by neoice** [mozilla-it/puppetctl#10]
I've never used `/etc/profile.d`, so I don't know if this is due to my shell being `zsh`:

`/etc/profile.d/profile.puppetctl.sh:5: condition expected: echo`

ps: I preferred it in the motd, but this probably is a cleaner solution :(

**Comment by bhourigan** [comment]
Hi neoice

It's been quite some time since you filed this issue, is this still a problem for you?

We thought about using /etc/motd but we don't have good control over how this file gets modified. Some other processes manipulate it and may strip out warning messages.

**Comment by neoice** [comment]
I'm running this without issue:

```
root@test1:~% cat /etc/profile.d/profile.puppetctl.sh 
# modified from upstream to support zsh
if [[ -f /var/run/puppetctl.status ]]; then
  if [[ $- != *i* ]] ; then
    # shell is not interactive, leave now!
    return
  fi
  echo -e "\033[1;31m$(cat /var/run/puppetctl.status)\033[0m"
fi
```

**Comment by neoice** [comment]
```
if [[ $- != *i* ]] ; then
    # shell is not interactive, leave now!
```

I believe this is a trick I stole from the default bashrc on Gentoo 5+ years ago. I've kept it in my profile since the time `sftp` stopped working because my bashrc was trying to do something a non-interactive terminal couldn't do.

here's the first doc I could find on how it works: http://tldp.org/LDP/abs/html/intandnonint.html#IITEST

**Comment by bhourigan** [comment]
Thanks for your contribution. I went ahead and modified the profile script to conditionally run your code if under zsh, otherwise, it will default to our previous detection mechanism.
