### ISSUE TITLE
When 'disable' has been run, you can't do 'run --noop'

### ISSUE THREAD

**Issue by solarce** [mozilla-it/puppetctl#8]
It'd be useful for be able to do 'run --noop' while things are disabled, as often you're disabling to make and test breaking changes

**Comment by gcoxmoz** [comment]
As of 6090e98ab525be863e73fe624040d3a22e689675 I've brought in the puppetctl we're running these days, and I'm calling this done.

When in `puppetctl disable`, you can't do `puppetctl run --noop`, but you can do `puppetctl enable ; puppetctl nooperate` to tell the host 'puppet is allowed to run (but only in noop mode).'  All future calls to `puppetctl run`, whether you or a cron, will automatically have `--noop` added.  Same rules apply as with disable, that this is all time-bound and it'll revert to operational mode after the time limit expires.

To @floatingatoll's point (but pivoting it slightly), pluginsync is gone now, but any items in the catalog that are `noop => true` WILL be executed when puppetctl is in nooperate mode.  IMO, that problem exists outside of puppetctl's realm, as puppet is doing what you told it to do.  If you're working in an area that someone decided to be `noop => true` then you'll need to take appropriate steps in your rollout plan.
